[package]
name = "rust_server"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3.26"
rand = "0.9.0-alpha.2"
regex = "1.10.6"
serde = { version = "1.0.209", features = ["derive"] }
actix-web = "4.9.0"
sqlx = "0.8.1"
